name: Actions 😎

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout -- Download the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache -- Cache the project for faster builds
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test -- In case we add unit tests later 
      #- name: Run tests
      # uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
         # githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build the project
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with: # We can add multiple platforms here in the future
          targetPlatform: StandaloneWindows
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
